#!/bin/bash
install_python3()
{
    yum -y install zlib*
    cd /usr/local/src/
    wget https://mirrors.huaweicloud.com/python/3.7.10/Python-3.7.10.tgz  -O Python-3.7.10.tgz
    tar xf Python-3.7.10.tgz
    cd Python-3.7.10
    ./configure --prefix=/usr/local/python3
    make && make install
    ln -s /usr/local/python3/bin/python3.7 /usr/bin/python3
    ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3
    python3 -V
    which python3
}
install_python3
